packages:
  - apps/*
  - packages/*

catalog:
  "@tanstack/react-query": 5.80.7
  "@trpc/client": 11.4.2
  "@trpc/react-query": 11.4.2
  "@trpc/server": 11.4.2
  react: 19.1.0
  react-dom: 19.1.0
  cors: 2.8.5
  express: 5.1.0
  ws: 8.18.2
  zod: 3.25.67

catalogMode: strict

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
